FROM python:3.8

WORKDIR /usr/src/app

COPY immocrawler ./immocrawler

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH /usr/src/app

CMD [ "python", "./immocrawler/worker.py" ]
